// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwvNXgZEoapA6ed-7SmrjjIEl8gKdJDc',
    appId: '1:928787371233:web:cc9b84e3bce704eebbd3a0',
    messagingSenderId: '928787371233',
    projectId: 'cw6new',
    authDomain: 'cw6new.firebaseapp.com',
    storageBucket: 'cw6new.firebasestorage.app',
    measurementId: 'G-ML2L3PYVMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVscd1OueiNBQ9VEb2be4ZnRHXAHl91Y',
    appId: '1:928787371233:android:49b81316bdc4f6f8bbd3a0',
    messagingSenderId: '928787371233',
    projectId: 'cw6new',
    storageBucket: 'cw6new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TxltKW1huWEBvjZHilj402H3bT9NWMk',
    appId: '1:928787371233:ios:bea5c8ba0694c320bbd3a0',
    messagingSenderId: '928787371233',
    projectId: 'cw6new',
    storageBucket: 'cw6new.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6TxltKW1huWEBvjZHilj402H3bT9NWMk',
    appId: '1:928787371233:ios:bea5c8ba0694c320bbd3a0',
    messagingSenderId: '928787371233',
    projectId: 'cw6new',
    storageBucket: 'cw6new.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSwvNXgZEoapA6ed-7SmrjjIEl8gKdJDc',
    appId: '1:928787371233:web:97e4c0b43b4d6654bbd3a0',
    messagingSenderId: '928787371233',
    projectId: 'cw6new',
    authDomain: 'cw6new.firebaseapp.com',
    storageBucket: 'cw6new.firebasestorage.app',
    measurementId: 'G-93WG87E98J',
  );

}